# Generated by Django 5.1.4 on 2025-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
